version: '3'

services:
  server:
    build: .
    ports:
      - "8080:8080"
    environment:
      - MONGO_PW=$MONGO_PW
      - JWT_SECRET=$JWT_SECRET
      - AWS_ACCESS=$AWS_ACCESS
      - AWS_SECRET=$AWS_SECRET